# Railway Deployment Configuration

[build]
builder = "NIXPACKS"

[[services]]
name = "stella"
source = "."

[[services.domains]]
domain = "stella-api.up.railway.app"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"

[services.healthcheck]
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3

[environments.production.variables]
DATABASE_URL = "${{ DATABASE_URL }}"
JWT_SECRET = "${{ JWT_SECRET }}"
WHATSAPP_ACCESS_TOKEN = "${{ WHATSAPP_ACCESS_TOKEN }}"
WHATSAPP_VERIFY_TOKEN = "${{ WHATSAPP_VERIFY_TOKEN }}"
WHATSAPP_PHONE_NUMBER_ID = "${{ WHATSAPP_PHONE_NUMBER_ID }}"
